apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
    app: elasticsearch
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: elasticsearch
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: elasticsearch
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        - containerPort: {{ .Values.service.transportTargetPort }}
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: bootstrap.memory_lock
          value: "true"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.periodSeconds }}
          timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          periodSeconds: {{ .Values.probe.periodSeconds }}
          timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-elasticsearch-pvc
      restartPolicy: Always
