DROP TABLE IF EXISTS cash;

CREATE TABLE cash (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        login VARCHAR(255) NOT NULL UNIQUE,
                        cash DECIMAL(10, 2) NOT NULL
);

INSERT INTO cash (login, cash)
VALUES
    ('alice_w', 41500.75),
    ('bor_g', 12345.00),
    ('kat_m', 23980.50);