DROP TABLE IF EXISTS account;

CREATE TABLE account (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         login VARCHAR(255) NOT NULL UNIQUE,
                         first_name VARCHAR(255) NOT NULL,
                         last_name VARCHAR(255) NOT NULL,
                         birth_date DATE
);

INSERT INTO account (login, first_name, last_name, birth_date)
VALUES
    ('alice_w', 'Алиса', 'Вальхалова', '1992-03-15'),
    ('bor_g', 'Борис', 'Головой', '1988-07-24'),
    ('kat_m', 'Екатерина', 'Миллер', '1995-11-05');