apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: keycloak
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.global.exposure.keycloak.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if eq .Values.global.exposure.keycloak.type "NodePort" }}
    nodePort: {{ .Values.global.exposure.keycloak.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
  selector:
    app: keycloak
    release: {{ .Release.Name }}
